### ISSUE TITLE
Provide a way to exclude certain files from the cache

### ISSUE THREAD

**Issue by JudahGabriel** [madskristensen/WebEssentials.AspNetCore.ServiceWorker#10]
Continuing from issue #8, we should provide a way for users to exclude certain request patterns from the cache.

For my scenario, I need to exclude all .mp3 files. Something like:

```
services.AddProgressiveWebApp(new PwaOptions
{
     // Don't cache MP3s, nor any request from mycdn.com/bigfiles
     RoutesToExcludeFromCache = ".mp3, https://mycdn.com/bigfiles/"
})
```

Not hard set on that syntax, opened to suggestions.

**Comment by JudahGabriel** [comment]
Mads, I'm willing to do the work and submit a PR for this. Are you cool with the above syntax? Or did you have a different idea how to exclude certain file types from the cache?

**Comment by JudahGabriel** [comment]
Rather than a .RoutesToExcludeFromCache, I realized what I really need is a "cache only the fingerprinted resources" strategy. I'm going to submit a PR for that.

**Comment by JudahGabriel** [comment]
Now that the CacheFingerprinted strategy is implemented, this issue is solved.

**Comment by bradmatt275** [comment]
I know this issue has been closed with an alternative solution, but this would be a great option to have.

For example it would be useful to exclude API calls and external requests from getting cached. 

While this can be done using the CacheFingerprinted strategy it prevents additional assets from caching, unless specified manually in the pre-cache.
