### ISSUE TITLE
Service Worker not registering in production environment

### ISSUE THREAD

**Issue by Mickael-Lamare** [madskristensen/WebEssentials.AspNetCore.ServiceWorker#14]
Hi, thanks for this nice package, it seems the service worker is not loading at the bottom of the body element in the html dom on my production environment only. Locally I can test the app and all seems ok when I test it with lighthouse.

I'm not sure what's wrong so here is the settings I'm using:

`services.AddProgressiveWebApp(
new PwaOptions
{
    Strategy = ServiceWorkerStrategy.CacheFirst,
    RegisterServiceWorker = true,
    RegisterWebmanifest = true
}, "manifest.json");`

whithout the manifest.json string it wasn't adding the meta and link tags in the head.

Could you try to help me out with this issue please?

**Comment by Mickael-Lamare** [comment]
fixed by unregistering the service worker and manually adding the script tag at the end of the body tag.
weird fix but it does the trick.

**Comment by mashbrno** [comment]
@DavidWhittingham I've pushed yesterday a pull request with SSL offloading support - it adds option `AllowHttp` which skips IsHttps checks.

**Comment by DavidWhittingham** [comment]
Thanks @mashbrno, was going to look at doing something similar myself, but writing up my above comment was about the last thing I did before going on holiday for a week, so haven't had the chance.  Cheers 👍
