### ISSUE TITLE
Inline service worker script fails to register with restrictive Csp policy

### ISSUE THREAD

**Issue by ashleybroughton** [madskristensen/WebEssentials.AspNetCore.ServiceWorker#30]
Using a content-security-policy of 'self' for script sources will make the `<script>` tag added by the following line of code to fail. At current, there appears to be no built-in way to include a nonce for this script tag.

```csharp
public void ConfigureServices(IServieCollection services)
    // ...
    services.AddProgressiveWebApp();
}
```

How do we enable this script tag to work without allowing unsafe-inline for script sources in Csp?

**Comment by ashleybroughton** [comment]
It seems that the NWebSec [CspNonceTagHelper](https://github.com/NWebsec/NWebsec/blob/081c95879055cf864dcc78bdf0f9afd24eb645e0/src/NWebsec.AspNetCore.Mvc.TagHelpers/CspNonceTagHelper.cs) inherits TagHelper without overriding [Order](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.razor.taghelpers.taghelper.order?view=aspnetcore-2.1) which makes it default to a value of 0.

Whereas [ServiceWorkerTagHelperComponent](https://github.com/GPavlovic/WebEssentials.AspNetCore.ServiceWorker/blob/abe6a2bbc13e2de75ee69e3b6f92599ef1ed74cf/src/ServiceWorker/ServiceWorkerTagHelperComponent.cs#L26) overrides the Order with a value of 100.

As TagHelpers are executed in lowest order first, the script tag for the service worker will not exist when NWebSec executes.

**Comment by RaceProUK** [comment]
I'm currently seeing this issue in a ASP.NET Core 3.1 app I'm building, and I'm wondering whether it's a genuine issue or if I'm just doing something wrong.

The code I'm using to set up the manifest and service worker is below:
```c#
            services.AddProgressiveWebApp(new PwaOptions
            {
                CacheId = "<cacheId>",
                Strategy = ServiceWorkerStrategy.Minimal,
                OfflineRoute = "offline.htm",
                RoutesToPreCache = "/Home/Index",
                RegisterServiceWorker = true,
                RegisterWebmanifest = true,
                EnableCspNonce = true
            });
```

This results in this HTML snippet:
```html
<script nws-csp-add-nonce='true'>'serviceWorker'in navigator&&navigator.serviceWorker.register('/serviceworker', { scope: '/' })</script>
```
instead of the expected
```html
<script nonce='<nonceValue>'>'serviceWorker'in navigator&&navigator.serviceWorker.register('/serviceworker', { scope: '/' })</script>
```

Package versions in use:
WebEssentials.AspNetCore.ServiceWorker 1.0.59
NWebsec.AspNetCore.Mvc.TagHelpers 3.0.0
