### ISSUE TITLE
How to apply app shell architecture?

### ISSUE THREAD

**Issue by floatorhead** [madskristensen/WebEssentials.AspNetCore.ServiceWorker#39]
Hi,

I would like to set up an app shell architecture including dynamic content which is not cached. Therefore, I would explicitly have to cache my index.cshtml with the CacheFingerprinted strategy. This does not seem possible.
The documentation states "This strategy is useful for scenarios in which you don't wish to cache certain resources [...] but still wish to cache the app core assets (HTML, CSS, JS)."
How can HTML be cached?

Thanks in advance.

**Comment by JudahGabriel** [comment]
I built the CacheFingerprinted strategy. I built it for SPA purposes, caching .html files. It wasn't designed for HTML generated from a .cshtml.

CacheFingerprinted will attempt to cache anything that has an ?v= query string. So you could perhaps cache it by redirecting your HomeController.Index method to append a ?v= query string. But a better option would be rolling a new cache strategy.

**Comment by floatorhead** [comment]
Thank you for your quick reply!
That's bad news for me, but I recognized, that in CacheFirst strategy the html from my index.cshtml and my partial view is indeed cached by my service worker. When I reload in offline mode, devtools tells me a file simply named "localhost" (I'm doing this with a test app on a local server) gets loaded from service worker. At the same time for my service worker cache storage, it shows me entries for "/" and "/Home/partialView1" and shows 0 for Content-Length of both...
I'm having a hard time to grasp this, but I might still just try the option of redirecting.

**Comment by floatorhead** [comment]
Do you happen do have a certain idea on how to redirect a Controller.Index method to append the ?v= query string? I didn't find out about how to apptoach this.

**Comment by JudahGabriel** [comment]
I think you can check if it has a query string in the request - maybe something like Request.Url.Query. If no query string, you can just do this.Redirect("/?v=1").

**Comment by JudahGabriel** [comment]
(Again, you'd need to do this for every Razor view. If you have a lot of them, I'd suggest rolling your own Cache strategy. It's pretty simple - I rolled CacheFingerprinted in about an hour or two.

**Comment by floatorhead** [comment]
Thanks a lot for the tip, I'll give it a go.
