### ISSUE TITLE
Unable to resolve service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' while attempting to activate 'WebEssentials.AspNetCore.Pwa.ServiceWorkerTagHelperComponent'

### ISSUE THREAD

**Issue by mpaine-act** [madskristensen/WebEssentials.AspNetCore.ServiceWorker#4]
Hi, I just wanted to let you know I had to fix your sample code by adding a DI singleton to ConfigureServices (in case anyone has this problem too).

```
services.AddMvc();
services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddProgressiveWebApp();
```

Thanks

**Comment by madskristensen** [comment]
This should be fixed in the latest release. Can you verify please?

**Comment by mpaine-act** [comment]
I have the same problem with 1.0.22 release.  Did you want me to try without using NuGet package?

**Comment by madskristensen** [comment]
This should be fixed in the latest release

**Comment by madskristensen** [comment]
Sorry, my bad. You should use the NuGet package **WebEssentials.AspNetCore.ServiceWorker** instead. The fix is in that one

**Comment by adigerati** [comment]
Just starting out. Used NuGet and got version 1.0.49.

Googled the error I was getting, ended up in this thread.

Had to add

> services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>()

in order to make it work.

**Comment by orilon** [comment]
Thanks @mpaine-act. ;) 
Same, had to add  
> ```
> services.AddMvc();
> services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
> services.AddProgressiveWebApp();
> ```
to get it to work.
_fyi, you need to add the following using directive for this to work:_
`using Microsoft.Extensions.DependencyInjection.Extensions;`

**Comment by dayport** [comment]
It appears this only happens when PwaOptions are not given, I found that it is because the TryAddSingleton was missing inside the first definition of AddServiceWorker function on line 20 of ServiceCollectionExtensions.
