### ISSUE TITLE
Appsettings pwa section seems to have no effect

### ISSUE THREAD

**Issue by JudahGabriel** [madskristensen/WebEssentials.AspNetCore.ServiceWorker#5]
Hi Mads,

The documentation appears to say that we can put PWA settings inside appsettings.json. I did this but it appears to have no effect:

```
// inside appsettings.json
{
  "pwa": {
    "strategy": "networkFirst"
  }
}

// inside startup.cs
services.AddProgressiveWebApp();
```

I would expect this to make networkFirst the strategy, but it appears to have no effect.

Running the sample locally under debugger shows that the PwaOptions constructor that takes an IConfiguration never gets called. And I see it's internal, and nothing in the library calls it.

Is this a bug? Or am I misunderstanding how the PWA settings inside appsettings.json is supposed to work? If it's a bug, I'd gladly submit a PR to fix it.

**Comment by madskristensen** [comment]
This is definitely a bug

**Comment by JudahGabriel** [comment]
I'll submit a PR with a fix today.
