### ISSUE TITLE
Uncaught (in promise) TypeError: Request failed

### ISSUE THREAD

**Issue by dannythomas13** [madskristensen/WebEssentials.AspNetCore.ServiceWorker#54]
I am getting the titled error once I have deployed my application to Azure, has anyone else done this with success?

I noticed that locally nothing was caching initially so I added the following to Startup.cs
`services.AddProgressiveWebApp(new PwaOptions
            {
                CacheId = "Worker 1.1",
                Strategy = ServiceWorkerStrategy.CacheFirst,
                RoutesToPreCache = "/Home/Index, /Shared/_Layout,/Shared/Error"
            });`

I was hoping all was then good as it successfully works offline on my machine but as mentioned once deployed to live environment it no longer works, feel free to take a look for yourselves at the error log in chrome: https://hello-pwa.azurewebsites.net/

**Comment by dayport** [comment]
This is because you are caching a path which does not exist:
https://hello-pwa.azurewebsites.net/Shared/_Layout and https://hello-pwa.azurewebsites.net/Shared/Error
