### ISSUE TITLE
Move to framework reference

### ISSUE THREAD

**Issue by thompson-tomo** [madskristensen/WebEssentials.AspNetCore.ServiceWorker#97]
**Is your feature request related to a problem? Please describe.**
In my dependency analysis a number of warnings are being flagged relating to the deprecated packages & they are bringing in package with CVE'S etc 

**Describe the solution you'd like**
The project moves to framework reference & the corresponding packages which are no longer needed are removed which means only the 2x Microsoft.Extensions packages remains

**Describe alternatives you've considered**
N/a

**Additional context**
https://github.com/dotnet/announcements/issues/217

**Comment by thompson-tomo** [comment]
@madskristensen Is this something you could look at or would you like a PR to expedite it?

**Comment by madskristensen** [comment]
A PR would be great. Thanks

**Comment by thompson-tomo** [comment]
all done @madskristensen. Note i am not sure what you would like the additional framework to be so set it to the min which is why the build is failing.

**Comment by thompson-tomo** [comment]
@madskristensen any chance of feedback/Acceptance of the pr?

**Comment by thompson-tomo** [comment]
Thanks for the release @madskristensen
